spring:
  application:
    name: admin-server
  
  boot:
    admin:
      # ===== CONFIGURACIÓN SSL (VERSIÓN 3.x) =====
      client:
        instance:
          tls:
            insecure: true           # ← IGNORA CERTIFICADOS NO CONFIABLES
            verify-hostname: false   # ← NO VERIFICA HOSTNAME
      
      # ===== CONFIGURACIÓN DE DESCRUBIMIENTO =====
      discovery:
        enabled: true                # ← Esto está BIEN, pero ahora al nivel correcto
        # ignored-services: actuator, consul  # (opcional) servicios a ignorar

# ===== SERVER =====
server:
  port: 9090

# ===== EUREKA =====
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    prefer-ip-address: true
    # hostname: localhost  # (opcional) mejor definirlo explícitamente