spring:
  application:
    name: admin-server
  
  # Necesario para que Spring Boot Admin use RestTemplate en lugar de WebClient
  main:
    web-application-type: servlet  # ← FORZAR a usar Servlet (no WebFlux)
  
  boot:
    admin:
      # Configuración SSL (aunque tu clase ya lo deshabilita globalmente)
      client:
        instance:
          tls:
            insecure: true           # ← Compatible con tu configuración
            verify-hostname: false   # ← Compatible con tu configuración
      
      # Descubrimiento de servicios
      discovery:
        enabled: true

server:
 port: 9090
eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka  # adapta al host/puerto de tu Eureka
   register-with-eureka: true
   fetch-registry: true
 instance:
   prefer-ip-address: true